#!/bin/bash

# With this script I want to apply a new and stricter filter based on missingness
# to my VCF. I will eliminate every SNP that has at least one missing genotype,
# leaving only positions which are genotyped in all samples. This will generate a
# new version of the VCF filtered for missingness (filter6-2.vcf). A VCF file
# with all the SNPs that have been removed will also be generated (variantswithmissingness.vcf).

# After applying this new missingness filter, I will use the VCF with the positions
# to filter out because of excessively high or low Depth, generated with
# the Depth_Filter_7.sh script. These are the "xxx.applydepthfilter.vcf" files
# of each dataset, which I will subtract from the new VCF filtered for missingness (filter6-2.vcf).
# This will generate a new version of the VCF filtered for Depth (filter7-2.vcf).

# Subtracting filter7-2.vcf from filter6-2.vcf will give me the list of variants
# filtered out by depth (variantswithdepth.vcf).

# This script will use the following softwares:

# BEDtools 2.28.0
# BCFtools 1.9

module load bedtools
module load bcftools

# AllIndividuals input VCF
INVCF=$LUSTRE/test/CatRef_vcfs/WholeGenome_cat_ref.filter5.vcf

# VCF Directory
OUTdir=/mnt/lustre/scratch/home/csic/ebd/jg2/test/CatRef_vcfs

##############################################
## Remove missingness from VCF - Filter 6-2 ##
##############################################

# Get list of variants with 1 or more samples with missing genotype
bcftools filter -i "N_MISSING >= 1" -Ov $INVCF \
> $OUTdir/variantswithmissingness.vcf

# Remove variants with 1 or more samples with missing genotype from VCF
bedtools subtract -a $INVCF \
-b $OUTdir/variantswithmissingness.vcf -header \
> $OUTdir/WholeGenome_cat_ref.filter6-2.vcf

##################################################################
## Remove variants with low or high depth from VCF - Filter 7-2 ##
##################################################################

# create a file for final list of variants
cp $OUTdir/WholeGenome_cat_ref.filter6-2.vcf $OUTdir/WholeGenome_cat_ref.filter7-2.vcf

# Array of files with variants to be filtered by depth (generated by Depth_Filter_7.sh)
applydepthARRAY=($(ls $OUTdir/*.applydepthfilter.vcf))

# Subtract variants from each dataset
for i in ${applydepthARRAY[@]}
  do
    echo $i
    bedtools subtract -a $OUTdir/WholeGenome_cat_ref.filter7-2.vcf \
	-b $i -header \
	> tmp && mv tmp $OUTdir/WholeGenome_cat_ref.filter7-2.vcf

done

########################################################
## Generate VCF with variants to be filtered by Depth ##
########################################################

# Get list of variants filtered out by depth
bedtools subtract -a $OUTdir/WholeGenome_cat_ref.filter6-2.vcf \
	-b $OUTdir/WholeGenome_cat_ref.filter7-2.vcf -header \
	> variantswithdepth.vcf
